# Base image
FROM node:24-alpine

# Set working directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy dependency manifests
COPY package.json ./

# Install dependencies
RUN pnpm install

# Copy rest of the app
COPY . .


CMD ["pnpm", "dev"]
